version: '3.8'

name: zapflix

services:
  downloader:
    build: .
    container_name: zapflix-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
      # Mount download directory if saving locally or needing Aria2 to see files
      # - /mnt/media:/media
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
